version: "3.8"
services:
    mongodb:
      image: mongo
      container_name: mongodb
      ports:
        - 27017:27017
      volumes:
        - data:/data
      environment:
        - MONGO_INITDB_ROOT_USERNAME=eduardouser
        - MONGO_INITDB_ROOT_PASSWORD=eduardopass
    mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=eduardouser
        - ME_CONFIG_MONGODB_ADMINPASSWORD=eduardopass
        - ME_CONFIG_MONGODB_SERVER=mongodb
    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      networks:
        - broker-kafka
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

    kafka:
      image: confluentinc/cp-kafka:latest
      networks:
        - broker-kafka
      depends_on:
        - zookeeper
      ports:
        - 9092:9092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    kafdrop:
      image: obsidiandynamics/kafdrop:latest
      networks:
        - broker-kafka
      depends_on:
        - kafka
      ports:
        - 9000:9000
      environment:
        KAFKA_BROKERCONNECT: kafka:29092
volumes:
  data: {}
networks:
  default:
    name: mongodb_network
  broker-kafka:
    driver: bridge